special_rules:
  初診60分:
  - 名駅さくら歯科
  - 金沢さくら医院
staff_by_clinic:
  ありす歯科:
    all_staff: []
    disabled: []
    doctors:
    - 加藤
    - 印南
    - 古川
    - 真鍋
    hygienists:
    - 尾関
    - 籔下
    web_booking:
    - 加藤
    - 古川
    - 印南
    - 真鍋
    - 籔下
    - 尾関
  きた矯正歯科:
    all_staff: []
    doctors: []
    hygienists: []
  きらり大森:
    all_staff: []
    doctors: []
    hygienists: []
  さくら歯科:
    all_staff: []
    disabled: []
    doctors:
    - 今川Cキャンセル/変更30％以
    - 今川キャンセル/変更10％台迄
    - 今川Ｂキャンセル/変更20％台
    - 堂東
    - 東Aキャンセル/変更20％台
    - 酒井A
    hygienists:
    - 三島
    - 小池
    - 尾関
    - 柴田
    - 渡辺
    - 渡
    - 菊谷
    - 赤松
    web_booking:
    - 今川キャンセル/変更10％台迄
    - 今川Ｂキャンセル/変更20％台
    - 今川Cキャンセル/変更30％以
    - 東Aキャンセル/変更20％台
    - 酒井A
    - 菊谷
    - 堂東
    - 三島
    - 柴田
    - 渡辺
    - 渡
    - 尾関
    - 赤松
    - 小池
  たんぽぽ歯科:
    all_staff: []
    doctors:
    - えりな
    - 園田
    - 吉冨
    - 大口
    - 萩原
    - 蔵
    hygienists:
    - 前澤
    - 山本
    - 奥村
    - 長谷川
    web_booking:
    - えりな
    - 蔵
    - 園田
    - 吉冨
    - 萩原
    - 大口
    - 奥村
    - 長谷川
    - 前澤
    - 山本
    - 金澤
  クローバー歯科:
    all_staff: []
    doctors:
    - 岩井
    - 蕪木
    - 高田
    - 松澤
    - 井上
    - 出井
    hygienists:
    - 宮本
    - 馬渕
    - 河野
    - 中村
    - 上岡
    - 久保
    - 藤田
    web_booking:
    - 岩井
    - 蕪木
    - 高田
    - 松澤
    - 井上
    - 出井
    - 馬渕
    - 河野
    - 久保
    - 中村
    - 上岡
  ヒロデンタルクリニック:
    all_staff: []
    doctors: []
    hygienists: []
  名駅さくら医院・歯科・皮膚科（歯科）:
    all_staff: []
    doctors: []
    hygienists: []
  日進赤池たんぽぽ歯科:
    all_staff: []
    doctors:
    - ヘルプDr
    - 柿崎A
    - 柿崎B
    - 永井
    - 柿木
    - 筒木
    hygienists:
    - DHヘルプ
    - 西山
    - 金田
    - 久世
    - 阿部
    - 佐藤
    web_booking:
    - 柿崎A
    - 西山
  春日井きらり歯科:
    all_staff: []
    doctors:
    - 鈴木
    - 沖
    - 園田
    - 菊谷
    - 鈴木B
    - 足立
    - 原
    - 沖B
    hygienists:
    - 渡辺
    - 中屋
    - 伊藤め
    - 前澤
    - 粟田
    - 長谷川
    - 瀬古
    - 森
    - 川竹
    web_booking:
    - 鈴木
    - 沖
    - 園田
    - 菊谷
    - 渡辺
  春日井アップル歯科:
    all_staff: []
    doctors:
    - Dr大城A
    - Dr大城B
    - Dr柿崎A
    - Dr柿崎B
    - Dr奥田
    - Dr永井
    hygienists:
    - DHヘルプA
    - DH三浦
    - DH佐藤
    - DH木下
    - DH成瀬
    - DH萩
    - DH藤井
    web_booking:
    - Dr大城A
    - Dr柿崎A
    - DH佐藤
    - DH三浦
    - DH木下
    - DH萩
    - DH藤井
  松戸ありす歯科:
    all_staff: []
    doctors:
    - 二木
    - 二木３
    - 二木2
    - 西村2
    - 西村
    hygienists:
    - 永井
    - 田中さゆ
    - 小谷中
    - 松江
    - 青山
    web_booking:
    - 永井
    - 田中さゆ
    - 青山
    - 小谷中
  池下さくら歯科:
    all_staff: []
    doctors:
    - 橋本
    - 伊藤A
    - 伊藤B
    - 高木A
    - 高木B
    - 佐分利
    - 勝野
    - 足立
    - 藤井(口外)
    - 落合（60分）
    hygienists:
    - 神箸
    - 角正
    - 園原
    - 新美
    slot_threshold:
      doctor: 60
      hygienist: 60
    web_booking:
    - 高木A
    - 高木B
    - 佐分利
    - 神箸
    - 角正
    - 園原
  流山ありす歯科・矯正歯科:
    all_staff: []
    doctors:
    - 松原
    - 松原2
    - 蕪木
    - 小川
    hygienists:
    - 橋本
    - 眞野
    - 藤田
    - 海老原
    web_booking:
    - 松原
    - 蕪木
    - 小川
    - 橋本
    - 眞野
    - 藤田
  流山ハピネス歯科:
    all_staff: []
    disabled: []
    doctors:
    - 牧村
    - 牧村２
    - 青柳
    - 松原
    - 淺野
    - 兼原
    - 小川
    - 三枝
    - 網野
    hygienists:
    - 塩澤
    - 内山
    - 髙栁
    - 赤川
    - 飯岡
    web_booking:
    - 牧村
    - 青柳
    - 松原
    - 淺野
    - 兼原
    - 塩澤
    - 内山
  町屋さくら歯科・矯正歯科:
    all_staff: []
    doctors: []
    hygienists: []
  金沢さくら医院（歯科）:
    all_staff: []
    doctors: []
    hygienists: []
  長久手さくら歯科・矯正歯科:
    all_staff: []
    doctors: []
    hygienists: []
