special_rules:
  初診60分:
  - 名駅さくら歯科
  - 金沢さくら医院
staff_by_clinic:
  ありす歯科:
    all_staff:
    - 加藤
    - 加藤B
    - 日比
    - 橋本
    - 古川
    - 印南
    - 真鍋
    - 梅田
    - 足立
    - 原
    - 高橋
    - 岡田
    - 急患.SP
    - TC
    - 籔下
    - 尾関
    - 岸
    - 中屋
    - 粟田
    - 瀬古
    - 尾関好
    - 黒濱相談・診断
    - 黒濱checkA
    - 黒濱MRC
    - 黒濱checkB
    disabled: []
    doctors:
    - 加藤
    - 印南
    - 古川
    - 真鍋
    hygienists:
    - 尾関
    - 籔下
    web_booking:
    - 加藤
    - 古川
    - 印南
    - 真鍋
    - 籔下
    - 尾関
  きた矯正歯科:
    all_staff:
    - 院長（初診診断
    - Dr喜多
    - Dr鈴木
    - Dr山崎
    - DH今村
    - DH松比良
    - DH坪井
    - 急患
    - メモ
    doctors: []
    hygienists: []
  きらり大森:
    all_staff:
    - Dr
    - Dr秋葉
    - Dr秋葉B
    - Dr木谷
    - Dr木谷B
    - Dr黒潮
    - Dr黒潮B
    - Dr松坂
    - Dr松坂B
    - Dr冨士谷
    - Dr大鶴
    - Dr岡本
    - Dr稲川・高橋
    - Dr稲川高橋B
    - Dr梶
    - Dr梶B
    - Dr梶C
    - 空閑
    - 空閑B
    - DH佐藤
    - DH祢津
    - DH大石
    - DH小澤
    - DH中澤
    - DH
    - TC
    - メモ
    - SP急患
    - キャンセル
    doctors: []
    hygienists: []
  さくら歯科:
    all_staff:
    - 橋本Ａ
    - 橋本Ｂ
    - 今川キャンセル/変更10％台迄
    - 今川Ｂキャンセル/変更20％台
    - 今川Cキャンセル/変更30％以
    - 東Aキャンセル/変更20％台
    - 東Bキャンセル/変更30％以上
    - 酒井A
    - 酒井B
    - 菊谷
    - 堂東
    - 川原
    - 三島
    - 柴田
    - 渡辺
    - 渡
    - 尾関
    - 赤松
    - 小池
    - 賀田野
    - ヘルプDH
    - SP/急患
    - 初診
    - 初診・終了コンサル
    - MFT,RTcheck
    - 黒濱相談診断
    - ワイヤー
    - インビザ
    - 訪問①
    - 訪問②
    - 訪問③
    - 訪問④
    - 訪問⑤
    - 訪問⑥
    - 訪問⑦
    - 訪問⑧
    - 訪問⑨
    - 長久手
    disabled: []
    doctors:
    - 今川Cキャンセル/変更30％以
    - 今川キャンセル/変更10％台迄
    - 今川Ｂキャンセル/変更20％台
    - 堂東
    - 東Aキャンセル/変更20％台
    - 酒井A
    hygienists:
    - 三島
    - 小池
    - 尾関
    - 柴田
    - 渡辺
    - 渡
    - 菊谷
    - 赤松
    web_booking:
    - 今川キャンセル/変更10％台迄
    - 今川Ｂキャンセル/変更20％台
    - 今川Cキャンセル/変更30％以
    - 東Aキャンセル/変更20％台
    - 酒井A
    - 菊谷
    - 堂東
    - 三島
    - 柴田
    - 渡辺
    - 渡
    - 尾関
    - 赤松
    - 小池
  たんぽぽ歯科:
    all_staff:
    - えりな
    - 蔵
    - 園田
    - 吉冨
    - 萩原
    - 大口
    - 岡田
    - 高橋
    - 外科
    - TCシルハ
    - 初診
    - 急患/SP
    - 奥村
    - 長谷川
    - 鈴木
    - 前澤
    - 山本
    - 伊藤
    - 飯田相談
    - 飯田調整
    - 黒濱相談
    - 黒濱ワイヤー
    - MRC/RTcheck
    - 黒濱インビザ
    - 梶相談
    - 梶ワイヤー
    - 梶小児インビザ
    doctors:
    - えりな
    - 園田
    - 吉冨
    - 大口
    - 萩原
    - 蔵
    hygienists:
    - 前澤
    - 山本
    - 奥村
    - 長谷川
    web_booking:
    - えりな
    - 蔵
    - 園田
    - 吉冨
    - 萩原
    - 大口
    - 奥村
    - 長谷川
    - 前澤
    - 山本
    - 金澤
  クローバー歯科:
    all_staff:
    - ＷＥＢ初診
    - 岩井
    - 蕪木
    - 高田
    - 松澤
    - 井上
    - 出井
    - 髙木治療
    - 宮本
    - 馬渕
    - 河野
    - 中村
    - 上岡
    - 久保
    - 藤田
    - TC/SP
    doctors:
    - 岩井
    - 蕪木
    - 高田
    - 松澤
    - 井上
    - 出井
    hygienists:
    - 宮本
    - 馬渕
    - 河野
    - 中村
    - 上岡
    - 久保
    - 藤田
    web_booking:
    - 岩井
    - 蕪木
    - 高田
    - 松澤
    - 井上
    - 出井
    - 馬渕
    - 河野
    - 久保
    - 中村
    - 上岡
  ヒロデンタルクリニック:
    all_staff:
    - 上手
    - 赤木
    - 市位
    - 藤森
    - 中村
    - 長谷川
    - 石田
    - 坂本
    - 梶
    - 柿崎
    - 担当医指定なし
    - 急患
    - 矯正相談
    - 小島
    - 中山
    - 尾﨑
    - 相澤
    - 久保田
    - 藤本
    - 浦瀬
    - 担当者指定なし
    - TC
    doctors: []
    hygienists: []
  名駅さくら医院・歯科・皮膚科（歯科）:
    all_staff:
    - 阪上
    - 阪上B
    - 阪上DH
    - 伊藤(允)
    - 伊藤(允)B
    - 柿木
    - 柿木B
    - 日比
    - 日比B
    - 市橋
    - 市橋B
    - 黄
    - 黄B
    - 大橋
    - 大橋B
    - 木本
    - 富士谷
    - 冨士谷B
    - 大沼
    - 大沼B
    - 橋本
    - 橋本Ｂ
    - Dr.希望なし
    - 梶
    - 梶B
    - 梶C
    - 空閑
    - 岡
    - 矯正B
    - 佐分利
    - 冨士谷
    - 田中
    - 田中B
    - 佐藤
    - 中村
    - 川竹
    - 石川
    - 松本
    - 伊藤(楓)
    - 吉田
    - 村田
    - 鈴木
    - 長瀬
    - 桟敷
    - WEB
    - TC
    - メモ
    - 連絡
    doctors: []
    hygienists: []
  日進赤池たんぽぽ歯科:
    all_staff:
    - ＳＰ/急患
    - 柿崎A
    - 柿崎B
    - 永井
    - 柿木
    - ヘルプDr
    - 筒木
    - TC
    - 岡①
    - 岡②
    - 空閑①
    - 空閑②
    - 西山
    - 金田
    - 久世
    - 阿部
    - 佐藤
    - DHヘルプ
    doctors:
    - ヘルプDr
    - 柿崎A
    - 柿崎B
    - 永井
    - 柿木
    - 筒木
    hygienists:
    - DHヘルプ
    - 西山
    - 金田
    - 久世
    - 阿部
    - 佐藤
    web_booking:
    - 柿崎A
    - 西山
  春日井きらり歯科:
    all_staff:
    - 初診・急患
    - 鈴木
    - 鈴木B
    - 沖
    - 沖B
    - 園田
    - 菊谷
    - 原
    - 足立
    - 瀬古
    - 森
    - 伊藤め
    - 長谷川
    - 渡辺
    - 粟田
    - 中屋
    - 川竹
    - 前澤
    - TC
    - 岡
    - 岡B
    doctors:
    - 鈴木
    - 沖
    - 園田
    - 菊谷
    - 鈴木B
    - 足立
    - 原
    - 沖B
    hygienists:
    - 渡辺
    - 中屋
    - 伊藤め
    - 前澤
    - 粟田
    - 長谷川
    - 瀬古
    - 森
    - 川竹
    web_booking:
    - 鈴木
    - 沖
    - 園田
    - 菊谷
    - 渡辺
  春日井アップル歯科:
    all_staff:
    - Dr大城A
    - Dr大城B
    - Dr柿崎A
    - Dr柿崎B
    - Dr奥田
    - Dr永井
    - SP/ 急患
    - TC
    - NG
    - DH佐藤
    - DH三浦
    - DH木下
    - DH萩
    - DH藤井
    - DHヘルプA
    - 黒濱相談
    - 黒濱A
    - 黒濱B
    - MRC
    - 岡A
    - 岡B
    doctors:
    - Dr大城A
    - Dr大城B
    - Dr柿崎A
    - Dr柿崎B
    - Dr奥田
    - Dr永井
    hygienists:
    - DHヘルプA
    - DH三浦
    - DH佐藤
    - DH木下
    - DH成瀬
    - DH萩
    - DH藤井
    web_booking:
    - Dr大城A
    - Dr柿崎A
    - DH佐藤
    - DH三浦
    - DH木下
    - DH萩
    - DH藤井
  松戸ありす歯科:
    all_staff:
    - 二木
    - 二木2
    - 二木３
    - 西村
    - 西村2
    - 千葉
    - 井波
    - 松本
    - 松本2
    - 永井
    - 田中さゆ
    - 青山
    - 小谷中
    - 松江
    - TC枠
    - SP/急患
    doctors:
    - 二木
    - 二木３
    - 二木2
    - 西村2
    - 西村
    hygienists:
    - 永井
    - 田中さゆ
    - 小谷中
    - 松江
    - 青山
    web_booking:
    - 永井
    - 田中さゆ
    - 青山
    - 小谷中
  池下さくら歯科:
    all_staff:
    - 橋本
    - 伊藤A
    - 伊藤B
    - 高木A
    - 高木B
    - 佐分利
    - 勝野
    - 足立
    - 藤井(口外)
    - 落合（60分）
    - TC
    - 神箸
    - 角正
    - 園原
    - 新美
    - DH
    - SP
    - 中山check20
    - 中山相談30
    - 訪問①
    - 訪問②
    - 訪問③
    - 訪問④
    - 訪問⑤
    - 訪問⑥
    - 訪問⑦
    - 訪問⑧
    - 訪問⑨
    - 訪問浄心①
    - 訪問浄心②
    - 訪問浄心③
    - 訪問浄心④
    doctors:
    - 橋本
    - 伊藤A
    - 伊藤B
    - 高木A
    - 高木B
    - 佐分利
    - 勝野
    - 足立
    - 藤井(口外)
    - 落合（60分）
    hygienists:
    - 神箸
    - 角正
    - 園原
    - 新美
    slot_threshold:
      doctor: 60
      hygienist: 60
    web_booking:
    - 高木A
    - 高木B
    - 佐分利
    - 神箸
    - 角正
    - 園原
  流山ありす歯科・矯正歯科:
    all_staff:
    - 松原
    - 松原2
    - 蕪木
    - 小川
    - TC
    - 田畑
    - 江口
    - 江口2
    - 橋本
    - 眞野
    - 藤田
    - 海老原
    - TC
    - sp/抜糸
    - ＷＥＢ初診
    doctors:
    - 松原
    - 松原2
    - 蕪木
    - 小川
    hygienists:
    - 橋本
    - 眞野
    - 藤田
    - 海老原
    web_booking:
    - 松原
    - 蕪木
    - 小川
    - 橋本
    - 眞野
    - 藤田
  流山ハピネス歯科:
    all_staff:
    - 牧村
    - 牧村２
    - 初診枠
    - 一歳半検診
    - 青柳
    - 松原
    - 淺野
    - 兼原
    - 小川
    - 三枝
    - 網野
    - 江口
    - 今井
    - 千葉
    - 江田
    - 塩澤
    - 内山
    - 髙栁
    - 赤川
    - 飯岡
    - SP抜糸枠
    - ＴＣ
    - 中断カウントなし
    - 訪問(木谷)
    - 訪問(小川)
    - 訪問(佐久間)AM
    - 訪問(DH千葉①)
    - 訪問(DH千葉②)
    - 訪問(DH大森)
    disabled: []
    doctors:
    - 牧村
    - 牧村２
    - 青柳
    - 松原
    - 淺野
    - 兼原
    - 小川
    - 三枝
    - 網野
    hygienists:
    - 塩澤
    - 内山
    - 髙栁
    - 赤川
    - 飯岡
    web_booking:
    - 牧村
    - 青柳
    - 松原
    - 淺野
    - 兼原
    - 塩澤
    - 内山
  町屋さくら歯科・矯正歯科:
    all_staff:
    - 黒潮
    - 増田
    - 稲川
    - 高橋
    - 梶
    - 吉嶺
    - 千田
    - 西野
    - TC・SP・急
    doctors: []
    hygienists: []
  金沢さくら医院（歯科）:
    all_staff:
    - 井上
    - 矯正
    - 矯正B
    - 日比
    - 梅田
    - 森
    - 橋爪
    - 家後
    - ヘルプDH
    - 北野
    - 名護
    - 藤居
    - 萩原
    - SP/急患
    - 上から検診
    - TC
    doctors: []
    hygienists: []
  長久手さくら歯科・矯正歯科:
    all_staff:
    - Dr伊藤
    - Dr落合
    - Dr亀川
    - SP・急患
    - Dr岡
    - Dr黒濱
    - Dr橋本
    - Dr岩田
    - Dr願興寺
    - Dr西村
    - DH小森
    - DH山本愛
    - DH山本真
    - DH関口
    - DH久保
    - TC
    - TC矯正
    doctors: []
    hygienists: []
